
services:
  db:
    image: postgres:15
    container_name: gamefinder-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: gamefinder
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: gamefinder-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: