"""add users and ownership

Revision ID: dcaae109e56f
Revises: cc2a386e5a66
Create Date: 2026-05-08 01:17:06.470033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcaae109e56f'
down_revision: Union[str, Sequence[str], None] = 'cc2a386e5a66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),)
    op.add_column(
        "games",
        sa.Column("owner_id", sa.UUID(), nullable=True),)
    conn = op.get_bind()
    has_existing_games = conn.execute(
        sa.text("SELECT 1 FROM games LIMIT 1")).first()
    if has_existing_games:
        op.execute("""
            INSERT INTO users (id, email, password_hash, created_at)
            VALUES (
                '00000000-0000-0000-0000-000000000000',
                'migration@example.com',
                '!',
                NOW()
            )
        """)
        op.execute("""
            UPDATE games
            SET owner_id = '00000000-0000-0000-0000-000000000000'
            WHERE owner_id IS NULL
        """)
    op.alter_column(
        "games",
        "owner_id",
        nullable=False,)
    op.create_foreign_key(
        "fk_games_owner_id_users",
        "games",
        "users",
        ["owner_id"],
        ["id"],)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_games_owner_id_users",
        "games",
        type_="foreignkey"
    )
    op.drop_column("games", "owner_id")
    op.drop_table("users")
    # ### end Alembic commands ###
