import { createFileRoute, Link } from "@tanstack/react-router";
import { useRef, useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { AppShell } from "@/components/AppShell";
import { InlineError, Panel, SectionHeader } from "@/components/ui-bits";
import { confirmPsnImport, previewPsnImport, searchGames, type PsnImportPreviewItem, type PsnImportSelection } from "@/lib/api";

export const Route = createFileRoute("/psn-import")({ component: PsnImportPage });
type Row = PsnImportPreviewItem & { decision: "catalog" | "raw" | "skip"; catalogId: number | null; restored: boolean };

function PsnImportPage() {
  const [rows, setRows] = useState<Row[]>([]), [error, setError] = useState<string | null>(null), [fileName, setFileName] = useState<string | null>(null), [query, setQuery] = useState<Record<string, string>>({}), [results, setResults] = useState<Record<string, { id: number; name: string }[]>>({});
  const input = useRef<HTMLInputElement>(null), client = useQueryClient();
  const preview = useMutation({ mutationFn: previewPsnImport, onSuccess: data => { setRows(data.items.map(item => ({ ...item, decision: item.status === "matched" ? "catalog" : "skip", catalogId: item.igdb_id ?? null, restored: false }))); setError(null); }, onError: e => setError(e instanceof Error ? e.message : "Could not read export.") });
  const confirm = useMutation({ mutationFn: confirmPsnImport, onSuccess: () => client.invalidateQueries({ queryKey: ["library"] }), onError: e => setError(e instanceof Error ? e.message : "Could not import titles.") });
  const update = (token: string, patch: Partial<Row>) => setRows(current => current.map(row => row.candidate_token === token ? { ...row, ...patch } : row));
  const matched = rows.filter(r => r.status === "matched"), mapping = rows.filter(r => r.status === "needs_mapping" || r.restored), skipped = rows.filter(r => r.status === "suggested_skip" && !r.restored);
  const decisions: PsnImportSelection[] = rows.flatMap(r => r.decision === "catalog" && r.catalogId ? [{ candidate_token: r.candidate_token, action: "catalog" as const, catalog_id: r.catalogId }] : r.decision === "raw" ? [{ candidate_token: r.candidate_token, action: "raw" as const }] : []);
  async function search(row: Row) { const q = query[row.candidate_token]?.trim(); if (q) { const data = await searchGames({ query: q }); setResults(current => ({ ...current, [row.candidate_token]: data.results.filter((game): game is { id: number; name: string } => game.id !== null) })); } }
  const card = (row: Row, mappingCard = false) => <div key={row.candidate_token} className="rounded-xl border border-border bg-surface-2 p-4"><p className="font-bold">{row.title ?? row.source_title}</p><p className="text-sm text-muted-foreground">{row.source_title}</p>{row.reason && <p className="mt-1 text-xs text-muted-foreground">{row.reason}</p>}{mappingCard && <div className="mt-3 space-y-2"><div className="flex flex-wrap gap-2">{row.suggestions.map(s => <button key={s.id} onClick={() => update(row.candidate_token, { decision: "catalog", catalogId: s.id })} className="rounded border px-2 py-1 text-xs">Use {s.title}</button>)}<button onClick={() => update(row.candidate_token, { decision: "raw" })} className="rounded border px-2 py-1 text-xs">Import as PSN title</button><button onClick={() => update(row.candidate_token, { decision: "skip" })} className="rounded border px-2 py-1 text-xs">Skip</button></div><div className="flex gap-2"><input aria-label={`Search catalog for ${row.source_title}`} value={query[row.candidate_token] ?? ""} onChange={e => setQuery({ ...query, [row.candidate_token]: e.target.value })} className="rounded border px-2 py-1"/><button onClick={() => search(row)} className="rounded border px-2 py-1 text-xs">Search</button></div>{(results[row.candidate_token] ?? []).map(game => <button key={game.id} onClick={() => update(row.candidate_token, { decision: "catalog", catalogId: game.id })} className="mr-2 rounded border px-2 py-1 text-xs">Use {game.name}</button>)}</div>}</div>;
  return <AppShell><div className="mx-auto max-w-3xl"><Link to="/account">Back to profile</Link><h1 className="mt-4 text-4xl font-bold">Import your PlayStation library</h1><Panel className="mt-6 p-6"><SectionHeader title="Upload export" hint="XLSX, CSV or JSON"/><button onClick={() => input.current?.click()} className="rounded-xl bg-primary px-4 py-2 font-bold text-primary-foreground">Choose an export file</button><input ref={input} type="file" accept=".xlsx,.csv,.json" className="hidden" onChange={e => { const file=e.target.files?.[0]; if(file){setFileName(file.name);preview.mutate(file);}}}/>{fileName && <p>{preview.isPending ? `Reading ${fileName}…` : `Parsed from ${fileName}`}</p>}{error && <InlineError>{error}</InlineError>}</Panel>{rows.length > 0 && <Panel className="mt-6 space-y-6 p-6"><section aria-label="Catalog matches"><h2>Catalog matches ({matched.length})</h2>{matched.map(r => card(r))}</section><section aria-label="Need mapping"><h2>Need mapping ({mapping.length})</h2>{mapping.map(r => card(r, true))}</section><section aria-label="Suggested skip"><details><summary>Suggested skip ({skipped.length})</summary>{skipped.map(r => <div key={r.candidate_token} className="rounded border p-3"><p>{r.source_title}</p><button onClick={() => update(r.candidate_token,{restored:true,decision:"skip"})}>Restore to mapping</button></div>)}</details></section><p>{decisions.filter(d=>d.action==="catalog").length} catalog · {decisions.filter(d=>d.action==="raw").length} RAW · {rows.length-decisions.length} skipped</p><button disabled={!decisions.length || confirm.isPending} onClick={() => {if(decisions.some(d=>d.action==="raw")&&!window.confirm("Import RAW PSN titles without a catalog match?"))return;confirm.mutate(decisions);}} className="rounded-xl bg-primary px-4 py-2 font-bold text-primary-foreground">Import selected</button></Panel>}</div></AppShell>;
}
